version: '3.9'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www:cached
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports:
            - "9000:9000"
        networks:
            - laravel
    nginx:
        image: nginx:latest
        ports:
            - 81:80
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - .:/var/www:cached
        depends_on:
            - app
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
